apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasks-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasks-app
  template:
    metadata:
      labels:
        app: tasks-app
    spec:
      containers:
        - name: tasks-app-container
          image: tasks-app
          ports:
            - containerPort: 8080
          imagePullPolicy: IfNotPresent
